version: "3"
services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "awx"
      POSTGRES_PASSWORD: "awxpass"
      POSTGRES_DB: "awx"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdatavolume:/var/lib/postgresql/data:Z
    networks:
      - awxnet
  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
    networks:
      - awxnet
  memcached:
    image: memcached:alpine
    networks:
      - awxnet
  awx_web:
    image: ansible/awx_web:latest
    user: root
    ports:
      - 8052:8052
    environment:
      SECRET_KEY: "awxsecret"
      DATABASE_NAME: "awx"
      DATABASE_USER: "awx"
      DATABASE_PASSWORD: "awxpass"
      DATABASE_PORT: 5432
      DATABASE_HOST: "postgresql"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_VHOST: "awx"
      MEMCACHED_HOST: "memcached"
      MEMCACHED_PORT: "11211"
      AWX_ADMIN_USER: "admin"
      AWX_ADMIN_PASSWORD: "password"
    networks:
      - awxnet
  awx_task:
    image: ansible/awx_task:latest
    user: root
    environment:
      SECRET_KEY: "awxsecret"
      DATABASE_NAME: "awx"
      DATABASE_USER: "awx"
      DATABASE_PASSWORD: "awxpass"
      DATABASE_PORT: 5432
      DATABASE_HOST: "postgresql"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_VHOST: "awx"
      MEMCACHED_HOST: "memcached"
      MEMCACHED_PORT: "11211"
      AWX_ADMIN_USER: "admin"
      AWX_ADMIN_PASSWORD: "password"
    networks:
      - awxnet
networks:
  awxnet:
volumes:
  pgdatavolume:
